name: matrix
on: workflow_dispatch

jobs:
  node-version:
    strategy:
      matrix: 
        # the name "node_version" is customize, change be any name
        # it is an array
        node_version: [6, 8, 10]
        # the setting here would become a 3X3 matrix (node_version * os)
        # therefore, this job would run 9 times
          # macos-latest+6, macos-latest+8, macos-latest+10
          # ubuntu-latest+6, ubuntu-latest+8, ubuntu-latest+10
          # windows-latest+6, windows-latest+8, windows-latest+10
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        # the include function is not to include extra item to the array
        # the include function is to add extra variable for the specific array which is contain in the matrix
        # in the following case, when the matrix reached the combination: ubuntu+8
        # there would be an extra is_ubuntu_8 variable
        # for other combination, this value does not exist
        include:
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true"
        # this is to exclude the unnecessary item in matrix
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: windows-latest
            node_version: 8

      # ** the following options 
      # ** true = means if one of the job is failed, the other jobs in the matrix will stop
      # ** false = means all the jobs will run independent of the result of other jobs
      # **this is not mandatory
      # fail-fast: true

      # ** another option: max-parallel, this will limit the job to be run in parallel
      # ** by default, the GitHub will maximize the no. of jobs to be run in parallel
      # max-parallel: 2
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: log node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          # the value here would be change each time, just like an array
          # for (int vers : node_version)
          node-version: ${{ matrix.node_version }}
      - name: log node-version
        run: |
          node -v
          echo "IS_UBUNTU_8 = $IS_UBUNTU_8"